---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install lint dependencies
        run: pip3 install yamllint ansible-lint

      - name: Install required collections
        run: ansible-galaxy collection install community.docker

      - name: Install required roles
        run: ansible-galaxy install geerlingguy.pip kirill_zak.docker

      - name: Run linter
        run: |
          yamllint .
          ansible-lint

  test:
    name: Molecule
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      
      matrix:
        include:
          - distr: geerlingguy/docker-centos8
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-debian10
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-debian11
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-fedora35
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-fedora36
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-ubuntu2004
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-ubuntu1804
            command: "/usr/sbin/init"
          - distr: geerlingguy/docker-ubuntu2204
            command: "/usr/sbin/init"
          - distr: kirillzak/docker-almalinux9
            command: "/usr/sbin/init"

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint

      - name: Install required collections
        run: ansible-galaxy collection install community.docker

      - name: Install required roles
        run: ansible-galaxy install geerlingguy.pip kirill_zak.docker

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTR: ${{ matrix.distr }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.command }}
          MOLECULE_TAG: ${{ matrix.tag }}
